DarkPlacesEngine/DarkPlaces

server.h, sv_ents.c, sv_main.c, sv_send.c
Adds `sv_cullentities_trace_spectators`
Can save a lot of CPU time with several spectators on complex maps, should be especially helpful for tournament servers.
=> Make trace entity culling optional for spectators

sv_phys.c
After the player made some horizontal progress, and before stepping up, it's necessary to recalculate the remaining time and distance for the move.  Previously the step up made the player travel (up to) nearly the move's full distance, again.
Closes #9
=> sv_gameplayfix_stepmultipletimes 1: Prevent players moving too far/fast when stepping up a staircase

sv_phys.c
When the player is hard up against a solid surface trying to climb up, they are blocked from gaining any significant speed by the solid, so the distance they could potentially move into the solid at that speed can be well under 0.03125 units, causing the step up to fail.
The same can happen when the player is stepping up with less than 0.03125 units of distance left on their move, causing them to stop dead when climbing stairs at speed with `sv_gameplayfix_stepmultipletimes 1`.
Fixes #8 Stepping up is unreliable
=> sv_gameplayfix_stepmultipletimes 1: Make stepping up while jumping reliable

netconn.c
dpm.dpmaster.org has been serving as a xonotic master (as dpm4.xonotic.xyz and dpm6.xonotic.xyz) for three months now, and I offer it here in hopes it's of use.
Also worth noting that six is one slot shy of being able to hold the complete set of current Xonotic masters.
Closes #24
=> Add a third masterextra and default it to dpm.dpmaster.org

libcurl.c
Curl versions older than 7.57.0 (found on Debian Stretch and older) do not implicitly initialize openssl, which leads https requests to fail.
In the course of debugging this issue verbose curl requests were needed, so that has also been added as a cvar.
=> Curl improvements

keys.c, keys.h, menu.c, prvm_cmds.c, vid_sdl.c
Fixed inability to bind non-ascii keys, so that players can use their native keyboard layout for both chatting and fragging.
([See issues like this](https://gitlab.com/xonotic/darkplaces/-/issues/46))
Fixed only the first character being input when using an Input Method (Asian languages practice)
Signed-off-by: NaitLee <naitli@foxmail.com>
=> Fixed two keyboard bugs

gl_rmain.c
Fixes #100 
Applies Baker's fix so that lightstyle 0 properly affects the default lightmap when using q3bsp.
=> Apply default lightstyle to to lightmap when using q3bsp

draw.h, ft2.c, ft2.h, ft2_fontdefs.h, gl_draw.c
This patch is effort of half one year and more than 3 trials by 2 persons.
Several big problems in font rendering (`ft2`) were solved. Read more below.
Before merging, it is wise to look into the [code](https://github.com/NaitLee/darkplaces/tree/NaitLee/ft2-better-maps-for-bigblock-chars) and [give it some test](https://github.com/NaitLee/darkplaces/releases/tag/patch-snapshot-0) first.
----
**Patch summary:**
- Fix the overall problem stated in #49 with the idea “incremental maps”
- New API `Font_GetMapForChar` for better support, mostly because `mapch` can be dynamic; `FontMap_FindForChar` and `Font_LoadMapForIndex` become legacy, but still can be used (without `incmap` support, behaves as usual)
- The new CVar `r_font_disable_incmaps` for always using old mapping behavior, useful for …
=> Fix several long-lasting font rendering problems

.gitattributes
Updates `.gitattributes` file to force `*.qc` and `*.qh` files to use C syntax highlighting using `linguist-language` which helps with syntax highlighting on Github.
=> Force C syntax for qc and qh files on Github

.github/workflows/build.yml
Creates a Github action to build the Linux sdl-release executable for pull-requests and on commits to the master branch.
=> Use Github actions to compile Linux builds

client.h, snd_main.c, snd_main.h, snd_mix.c, view.c
daftmugi ported Ironwail's audio acoustic feature, muffling the intensity of sounds when the player is underwater, to the wrath-darkplaces repo. I've cherry-picked the commit (https://github.com/daftmugi/wrath-darkplaces/commit/d7322471d7f6564b69384723fc31e0b2ded4f2ff).
=> Muffle sounds when the player is under water

gl_rmain.c
Fixed #145 by changing `dupe` variable back from `unsigned int` to `int`.
=> Fix r_glsl_dumpshader segfault

sv_ccmds.c
Allows the command `give a #` to give the player armour, just like the other `give` commands. Based on the example code provided by Baker7. Fixes #132 .
=> Add support for a "give a" command to give player armour

keys.c
Can't use the "=+" key to increase the console text size because the code only wants "+"; ctrl+shift+= also does not work. Keypad + works. This patch makes it accept the = key as well as +. Fixes #110 .
=> Accept "ctrl" + "=" for increasing console text size

menu.c
Copies the text from the `modinfo.txt` into the name field for the mod list entry. If there is no text the mod directory name is used as before.
Fixes Alkaline 1.2 failing to appear in the mod list (its dir is `alk1.2`).
=> Use the text from modinfo.txt as the mod menu entry

cl_screen.c, console.c, console.h
Add new function `Con_CenterPrint` which can be used to print messages to the console, without showing onscreen, and with a "horizontal rule" above and below. Use `Con_CenterPrint` to log centerprint messages to the console.
Fixes #98
=> Print centerprint messages to the console

progsvm.h, prvm_cmds.c, prvm_edict.c, sv_save.c
Modified PRVM_ED_ParseEdict to determine whether it is loading a save or not, and unescape variables if loading a save. Fixes #81
=> Properly unescape escaped characters in save file when loading

gl_rmain.c
Updates the entity visibility check in `R_View_UpdateEntityVisible` so that with `r_novis 1` entities are rendered when the player is outside of the level.
Resolves #188 
`r_novis 0`
`r_novis 1`
=> Only use BoxTouchingVisibleLeafs when not using r_novis

pr_comp.h, prvm_edict.c, prvm_exec.c, prvm_execprogram.h
This reduces the struct from 20 to 16 bytes, and thus may save some RAM. It also may improve CPU cache behavior by keeping more QC code in L1 and L2 cache, and possibly also improve instruction processing inside the CPU as all statements are aligned the same way.
On `srv04`, this speeds up Xonotic's `serverbench` from 58.92s real, 57.72s user to 57.72s real, 56.59s user (median of 25).
Change suggested by @uis246.
=> Remove the `jumpabsolute` member from `mstatement_s`.

console.c, fs.c
I'm really late 🥲 With this patch, compiling darkplaces master with msys2 ucrt64 environment is back to normal.
History:
- A commit was introduced to have current working directory known by the engine to fix some mods:
- https://gitlab.com/xonotic/darkplaces/-/commit/1f4743e930b01c520372c570fb6c936ed461ee64
- To fix: https://github.com/DarkPlacesEngine/DarkPlaces/issues/172
- I submitted a patch, because that code breaks games in Windows non-ascii paths:
- https://gitlab.com/xonotic/darkplaces/-/merge_requests/153
- The `_getcwd` function used in the patch is causing segmentation fault in ucrt64 environment:
- https://gitlab.com/xonotic/darkplaces/-/issues/422
- We need a win32 native function to avoid this segmentation fault — this pull request
Closes …
=> fix(fs.c, windows, ucrt64): fix getcwd for windows ucrt64 builds

server.h, sv_main.c, sv_phys.c
Adds new cvar `sv_gameplayfix_nosquashentities` which, when enabled, will prevent entity hitboxes being resized when the entity is squashed by a mover. This means the entity can continue to interact with pushers and movers. Fixes #155.
=> Add sv_gameplayfix_nosquashentities to control entity hitbox squashing

pr_comp.h, prvm_edict.c, prvm_exec.c, prvm_execprogram.h, sv_main.c
This adds the following instructions:
* GLOBALADDRESS
* ADD_PIW
* LOADA_{F,V,S,ENT,FLD,FNC,I}
* LOAD_P
* LOADP_{F,V,S,ENT,FLD,FNC,I}
* Offset feature, and support for global pointers, for STOREP_{F,V,S,ENT,FLD,FNC,I}
It changes QC "address space" as follows:
* Before:
* [0x0, num_ents * num_fields[: entities
* After:
* [0x0, 0x80000000[: reserved (FTE puts strings and "malloc area" there)
* [0x80000000, 0x80000000 + num_globals[: globals
* [0x80000000 + num_globals, 0x80000000 + num_globals + num_ents * num_fields[: entities
This changes nothing visible, as these pointer values are generally invisible to well written QC code, however, writing to a NULL pointer notably now errors in the QC VM (previously, it would overwrite `world.modelindex`, which, I guess, may make the map go away, …
=> Add FTEQCC pointer instructions

client.h, gl_rmain.c
Removes the `freedecal` field, and as such, fixes some invariant violations found in issue #216 that appear to lead to engine crashes.
Performance should remain unchanged, as the decal expiry process performed full decal copies from end spots to unoccupied spots as part of its "shuffling" loop anyway. New decals are now always added to the end, and when a decal expires, it's now always replaced by the current last decal in the list. If only one decal were to expire per frame, this matches the previous behavior, so I am not expecting any visible differences due to decal Z index in regular gameplay from this either.
Fixes issue #216.
=> Simplify decal system.

console.c, gl_draw.c
Commits:
- 465d2925 Revert "Change directory text colour in console from blue to light cyan (https://github.com/DarkPlacesEngine/DarkPlaces/pull/197)"
This reverts commit https://github.com/DarkPlacesEngine/DarkPlaces/commit/0c17657b4a2562f6c1d9e0a0707faff825dd8ce5.
This was a band-aid fix to a single issue and does not address the root cause or any of the other issues where the Quake blue colour is not readable.
- a48ccf0
This is my attempt at making the Quake blue more readable.
---
The changes can be tested for example via `echo ^1aaa^2aaa^3aaa^4aaa^5aaa^6aaa^7aaa^8aaa^9aaa` or `playdemo` tab completion.
---
`gl_draw.c:862` has the colour definition of blue which is too dark to be readable in several cases. It is currently set to `#0000FF` in hex, pure blue. Changing this should be …
=> Change the shade of Quake blue to make it readable

progsvm.h, prvm_edict.c, prvm_exec.c, prvm_execprogram.h, qtypes.h
Suggested by Spoike.
Fixes #236
Also fixing existing bugs in OP_DIV_* (no division by zero check, and inaccuracy in OP_DIV_IF).
=> Implement a set of new QC opcodes for bit shifts and unsigned integer math.

prvm_edict.c, prvm_exec.c, prvm_execprogram.h
Also improve accuracy of `DIV_VF` a bit.
This matches FTEQW.
=> PRVM: Return NaN/inf values for divisions by zero.

.github/workflows/build.yml
Remove the Python installation step from the wasm-release pipeline job so that it can actually get to the engine compilation.
=> Remove Python installation from wasm-release job

fs.c
`ztk` gets allocated few lines before, but not deallocated in case of an error.
=> fs: fix memory leak when zlib's inflateInit fails

prvm_edict.c
Implement @Baker7's suggestion by updating `prvm_edictset` so that when no new value is provided it will instead call `prvm_edictget`, returning the current value. Resolves #213
=> Allow prvm_edictset to return the current value

prvm_edict.c, prvm_execprogram.h
LOADP/STOREP/GLOBALADDRESS fully replace it, and GADDRESS was always pretty much broken.
Also, block writes by GSTOREP to OFS_NULL which heavily break STOREP.
Fixes #278.
=> Deprecate the GLOAD/GSTOREP/GADDRESS instruction set.
